### ISSUE TITLE
Rolling TODO List

### ISSUE THREAD

**Issue by jordanbtucker** [jordanbtucker/json5-go#1]
**v1.0.0** (TODO list not yet finalized)
- [ ] Write public API. (The public API doesn't do anything right now. All working code is in non-exported functions.)
- [ ] Write tests. (I'm not even sure if this works yet. I translated it from the json5-net implementation.)
- [ ] Document everything.
- [ ] Determine whether the package or repository needs to be renamed. (Import path `github.com/jordanbtucker/json5-go` exports package `json5`. See [Organizing Go code](https://blog.golang.org/organizing-go-code).)

**Comment by mewmew** [comment]
Consider exporting the same API as [encoding/json](https://golang.org/pkg/encoding/json/) in the Go standard library. Since json5 is a superset of JSON, this would allow users to seamlessly start using json5 without having to change anything in their programs except the import path.

In particular, it would be great to have access to [MarshalIndent](https://golang.org/pkg/encoding/json/#example_MarshalIndent) for having JSON5 pretty-printed in a canonical fashion.

It would also be good to have [NewEncoder](https://golang.org/pkg/encoding/json/#NewEncoder) and [NewDecoder](https://golang.org/pkg/encoding/json/#NewDecoder). so users of the API may use arbitrary `io.Reader` and `io.Writer` values.
